{% set name = "Phosphoros" %}
{% set version = "1.6.2" %}
{% set build_number = 0 %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    git_rev: {{ version }}
    git_url: https://github.com/astrorama/Phosphoros.git
    patches:
      - trigger_compiler_id.patch

build:
    number: {{ build_number }}

test:
    commands:
        - $PREFIX/bin/Phosphoros --version

requirements:
    build:
        - python                             # [build_platform != target_platform]
        - cross-python_{{ target_platform }} # [build_platform != target_platform]
        - cython                             # [build_platform != target_platform]
        - qt >=5.12,<6                       # [build_platform != target_platform]
        - cmake >=3.0
        - make
        - {{ compiler('cxx') }}
        - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
        - {{ cdt('libx11-devel') }}          # [linux]
        - {{ cdt('libxext-devel') }}         # [linux]
        - {{ cdt('libxrender-devel') }}      # [linux]
        - {{ cdt('libxau-devel') }}          # [linux]
        - {{ cdt('mesa-libgl-devel') }}      # [linux]
        - {{ cdt('mesa-libegl-devel') }}     # [linux]
        - {{ cdt('mesa-dri-drivers') }}      # [linux]
        - {{ cdt('libxdamage') }}            # [linux]
        - {{ cdt('libxdamage-devel') }}      # [linux]
        - {{ cdt('libxxf86vm') }}            # [linux]
        - {{ cdt('libxfixes') }}             # [linux]
        - {{ cdt('libxfixes-devel') }}       # [linux]
        - {{ cdt('libselinux-devel') }}      # [linux]
        - libcxx<16
    host:
        - python
        - boost-cpp 
        - libcxx<16
        - phosphoroscore ==1.6.1
        - qt >=5.12,<6
        - cfitsio >=3.470
        - CCfits >=2.5
        - lxml >=4.5
        - pybind11 >=2.6
    run:
        - {{ pin_compatible('python', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('boost-cpp', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('libcxx', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('CCfits') }}
        - astropy
        - matplotlib
        - scipy
        - requests

test:
    commands:
        - $PREFIX/bin/Phosphoros --version

app:
    entry: Phosphoros GUI
    icon: phosphoros_64.png
    summary: A photometric redshift determination tool based on a template fitting method.
    description: A photometric redshift determination tool based on a template fitting method.
    own_environment: True

about:
    home: http://isdc.unige.ch/euclid/phosphoros/
    license: LGPL
    summary: A photometric redshift determination tool based on a template fitting method.

