package:
    name: phosphoros 
    version: {{ GIT_DESCRIBE_TAG }}

source:
    git_rev: develop
    git_url: https://{{ environ.get('GIT_USER', '') }}@gitlab.euclid-sgs.uk/SDC-CH/Phosphoros.git
    patches:
        - trigger_compiler_id.patch

build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

test:
    commands:
        - $PREFIX/bin/Phosphoros --version

requirements:
    build:
        - cmake >=3.0
        - make
        - {{ compiler('cxx') }}
        - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
        - {{ cdt('libx11-devel') }}          # [linux]
        - {{ cdt('libxext-devel') }}         # [linux]
        - {{ cdt('libxrender-devel') }}      # [linux]
        - {{ cdt('libxau-devel') }}          # [linux]
        - {{ cdt('mesa-libgl-devel') }}      # [linux]
        - {{ cdt('mesa-libegl-devel') }}     # [linux]
        - {{ cdt('mesa-dri-drivers') }}      # [linux]
        - {{ cdt('libxdamage') }}            # [linux]
        - {{ cdt('libxdamage-devel') }}      # [linux]
        - {{ cdt('libxxf86vm') }}            # [linux]
        - {{ cdt('libxfixes') }}             # [linux]
        - {{ cdt('libxfixes-devel') }}       # [linux]
        - {{ cdt('libselinux-devel') }}      # [linux]
    host:
        - elements ==5.8
        - alexandria ==2.15
        - phosphoroscore ==0.15
        - boost-cpp ==1.70
        - qt =5
        - cfitsio
        - CCfits
        - python
        - pytest
    run:
        - elements ==5.8
        - alexandria ==2.15
        - phosphoroscore ==0.15
        - boost-cpp ==1.70
        - qt =5
        - cfitsio
        - CCfits
        - astropy
        - matplotlib

test:
    commands:
        - $PREFIX/bin/Phosphoros --version

app:
    entry: Phosphoros GUI
    icon: phosphoros_64.png
    summary: A photometric redshift determination tool based on a template fitting method.
    description: A photometric redshift determination tool based on a template fitting method.
    own_environment: True

about:
    home: http://isdc.unige.ch/euclid/phosphoros/
    license: LGPL
    summary: A photometric redshift determination tool based on a template fitting method.

