package:
    name: phosphoros 
    version: "0.11"

source:
    url: https://bintray.com/astrorama/archives/download_file?file_path=Phosphoros-0.11.tar.gz

build:
    number: 3

requirements:
    build:
        - cmake >=3.0
        - make
        - {{ compiler('cxx') }}
        - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
        - {{ cdt('libx11-devel') }}          # [linux]
        - {{ cdt('libxext-devel') }}         # [linux]
        - {{ cdt('libxrender-devel') }}      # [linux]
        - {{ cdt('libxau-devel') }}          # [linux]
        - {{ cdt('mesa-libgl-devel') }}      # [linux]
        - {{ cdt('mesa-libegl-devel') }}     # [linux]
        - {{ cdt('mesa-dri-drivers') }}      # [linux]
        - {{ cdt('libxdamage') }}            # [linux]
        - {{ cdt('libxdamage-devel') }}      # [linux]
        - {{ cdt('libxxf86vm') }}            # [linux]
        - {{ cdt('libxfixes') }}             # [linux]
        - {{ cdt('libxfixes-devel') }}       # [linux]
        - {{ cdt('libselinux-devel') }}      # [linux]
    host:
        - elements ==5.2.2
        - alexandria ==2.13
        - phosphoroscore ==0.13
        - boost >=1.69
        - qt =5
        - cfitsio
        - CCfits
        - python
        - pytest
    run:
        - elements ==5.2.2
        - alexandria ==2.13
        - phosphoroscore ==0.13
        - boost >=1.69
        - qt =5
        - cfitsio
        - CCfits
        - astropy

test:
    commands:
        - $PREFIX/bin/python $PREFIX/bin/Phosphoros --version

app:
    entry: Phosphoros GUI
    icon: phosphoros_64.png
    summary: A photometric redshift determination tool based on a template fitting method.
    description: A photometric redshift determination tool based on a template fitting method.
    own_environment: True

about:
    home: http://isdc.unige.ch/euclid/phosphoros/
    license: LGPL
    summary: A photometric redshift determination tool based on a template fitting method.

